services:
  synthea:
    image: intersystemsdc/irisdemo-base-synthea:version-1.3.4
    volumes:
      - ./output:/output
    command: [
      "-p", "${PATIENT_COUNT}",
      "--exporter.csv.export=true"
    ]
