services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patient_mgmt
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    build: ./server
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: patient_mgmt
      PORT: 3001
      JWT_SECRET: dev_secret
      JWT_EXPIRES_IN: 1d
      EMAIL_HOST: mailpit
      EMAIL_PORT: 1025
      EMAIL_FROM: "Patient Management <no-reply@example.com>"
      CLIENT_URL: http://localhost:3002
      # Note: client exposed on host 3002, but origin uses 3002; app will still permit both
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"
    command: sh -c "node dist/main.js"

  client:
    build: ./client
    environment:
      REACT_APP_API_BASE_URL: http://localhost:3001
    depends_on:
      - server
    ports:
      - "3002:3000"

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1026:1025"
      - "8026:8025"


