services:
  oauth-server:
    build:
      context: ./oauth-server
      dockerfile: Dockerfile
    ports:
      - "${OAUTH_PORT:-3001}:${OAUTH_PORT:-3001}"
    volumes:
      - ./oauth-server:/app
      - /app/node_modules
    env_file:
      - ./.env           # root: single source of truth for all services
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      - nhs-network

  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    ports:
      - "${API_PORT:-4001}:${API_PORT:-4001}"
      - "9229:9229" # Node inspector for debugging
    volumes:
      - ./api-server:/app
      - /app/node_modules
    env_file:
      - ./.env              # root shared envs
    environment:
      - NODE_ENV=development
      - NHS_API_KEY=${NHS_API_KEY:?NHS_API_KEY not set in root .env}
      - NODE_OPTIONS=--inspect=0.0.0.0:9229
    command: npm run dev
    networks:
      - nhs-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_PORT:-3000}:${CLIENT_PORT:-3000}"
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./.env              # root: provides REACT_APP_* values
    environment:
      - PORT=${CLIENT_PORT:-3000}
      - HOST=0.0.0.0
      # Use root .env values with sane fallbacks for local dev
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING:-true}
      - WATCHPACK_POLLING=${WATCHPACK_POLLING:-true}
      - REACT_APP_OAUTH_BASE=${REACT_APP_OAUTH_BASE:-http://localhost:3001}
      - REACT_APP_API_BASE=${REACT_APP_API_BASE:-http://localhost:4001}
      - REACT_APP_CLIENT_ID=${REACT_APP_CLIENT_ID:-9c7c344a-51e3-41c0-a655-a3467f2aca57}
      - REACT_APP_REDIRECT_URI=${REACT_APP_REDIRECT_URI:-http://localhost:3000/callback}
      - REACT_APP_SCOPE=${REACT_APP_SCOPE:-openid basic_demographics email phone}
    command: npm start
    networks:
      - nhs-network
    depends_on:
      - oauth-server
      - api-server

networks:
  nhs-network:
    driver: bridge

volumes:
  node_modules:
