services:
  synthea:
    image: intersystemsdc/irisdemo-base-synthea:version-1.3.4
    volumes:
      - ./output:/output
    command: [
      "-p", "100",
      "--exporter.csv.export=true",
      "--exporter.fhir.export", "false",
      "--exporter.baseDirectory", "/output",
      "--generate.demographics.socioeconomic", "true",
      "--generate.lookup_tables", "true",
      "Massachusetts"
    ]
    networks:
      - triage-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - triage-network
    # No healthcheck as per official setup
    # The service will be ready when the API is responsive

  comparison:
    build: .
    volumes:
      - .:/app
      - ./output:/app/output
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - PYTHONUNBUFFERED=1
    depends_on:
      synthea:
        condition: service_completed_successfully
      ollama:
        condition: service_started
    networks:
      - triage-network
    command: >
      sh -c "chmod +x /app/init_ollama.sh && 
             /app/init_ollama.sh && 
             python -m pip install -r requirements.txt && 
             python -m simulation.compare_triage_systems"

networks:
  triage-network:
    driver: bridge

volumes:
  ollama_data:
