# Official Manchester Triage System (MTS) Configuration
# Based on peer-reviewed academic research and official sources

# PRIORITY LEVELS - Official MTS 5-category system
# Source: PMC5016055 - "Manchester Triage System: main flowcharts, discriminators and outcomes"
# Link: https://pmc.ncbi.nlm.nih.gov/articles/PMC5016055/
# Source: Storm-Versloot et al., 2014 - Emerg Med J. 2014;31:13-18
# DOI: 10.1136/emermed-2012-201099
priorities:
  1: 
    name: Immediate        # Red category
    color: Red
    max_wait_min: 0       # "immediate evaluation by a physician"
    weight: 0.05
  2: 
    name: Very Urgent     # Orange category  
    color: Orange
    max_wait_min: 10      # "evaluation within 10 minutes"
    weight: 0.15
  3: 
    name: Urgent          # Yellow category
    color: Yellow  
    max_wait_min: 60      # "60 minutes"
    weight: 0.30
  4: 
    name: Standard        # Green category
    color: Green
    max_wait_min: 120     # "2 hours"
    weight: 0.35
  5: 
    name: Non-urgent      # Blue category
    color: Blue
    max_wait_min: 240     # "4 hours"
    weight: 0.15

# ENCOUNTER PRIORITY MAPPING
# Source: Clinical practice guidelines and expert consensus
# Based on: NHS Emergency Care Data Set standards
# Reference: https://www.datadictionary.nhs.uk/
encounter_priority_map:
  emergency: [1, 2, 3]     # Life-threatening conditions
  ambulatory: [3, 4, 5]   # Outpatient conditions
  wellness: [4, 5]        # Preventive care
  outpatient: [3, 4, 5]   # Non-urgent medical care
  inpatient: [2, 3, 4]    # Hospital admissions
  urgentcare: [2, 3, 4]   # Urgent care presentations

default_priority: 4  # Standard (Green) - most common category

# GENERAL DISCRIMINATORS - Core MTS decision points
# Source: Mackway-Jones K et al. Emergency Triage, Manchester Triage Group. Second edition. Oxford: Blackwell Publishing Ltd; 2006
# ISBN: 978-0-7279-1787-2
# Official MTS Manual: https://www.triagenet.net/ (requires professional access)
general_discriminators:
  life_threat:
    # Immediate Priority (Red) discriminators
    airway_compromise: "Insecure airway, unable to maintain for any length of time"
    absence_of_breathing: "No respiration or respiratory effort for 10 seconds"  
    inadequate_breathing: "Failing to maintain adequate oxygenation, increased work, signs of exhaustion"
    absence_of_pulses: "Diagnosed after palpation over central pulse for 5 seconds"
    shock: "Classic signs: sweating, pallor, tachycardia, hypotension, reduced consciousness"
    currently_fitting: "Active seizure - Priority 1"
    unresponsive_child: "No response to stimuli in pediatric patients - Priority 1"

  consciousness_level_adults:
    # Source: Standard MTS discriminator definitions
    altered_conscious_level: "Not fully alert or responsive - Priority 2"
    history_of_unconsciousness: "Recent loss of consciousness - Priority 3"
    
  consciousness_level_children:
    # Source: Van Veen et al., 2008 - BMJ pediatric MTS validation
    # DOI: 10.1136/bmj.a1501
    # Link: https://www.bmj.com/content/337/bmj.a1501
    responds_to_voice_pain: "Responds only to voice or pain - Priority 2"
    history_of_unconsciousness: "Recent loss of consciousness - Priority 3"

  hemorrhage:
    # Source: Standard MTS bleeding assessment criteria
    exsanguinating: "Death will ensue rapidly unless stopped - Priority 1"
    uncontrollable_major: "Not controlled by sustained pressure, heavy flow - Priority 2"
    uncontrollable_minor: "Blood continues to flow slightly or ooze - Priority 3"

  temperature:
    # Source: Nijman et al., 2011 - Arch Dis Child fever discriminators
    # DOI: 10.1136/adc.2010.207845
    # Link: https://adc.bmj.com/content/96/8/715
    # Study: "Can urgency classification of the Manchester triage system predict serious bacterial infections in febrile children?"
    very_hot: "≥41°C, skin feels very hot, ≥1yr - Priority 2"
    hot: "≥38.5°C, skin feels hot - Priority 3"  
    hot_baby: "≥38.5°C in <1yr - Priority 2 (pediatric-specific)"
    warm: "<38.5°C - Priority 4"

  pain_assessment:
    # Source: Standard MTS pain scoring methodology
    severe_pain: "8-10/10 pain score - Priority 2"
    moderate_pain: "5-7/10 pain score - Priority 3"
    mild_pain: "1-4/10 pain score - Priority 4"

# OFFICIAL MTS FLOWCHARTS
# Source: PMC5016055 states "The MTS provides a list of 52 flowcharts, 49 suitable for children"
# Link: https://pmc.ncbi.nlm.nih.gov/articles/PMC5016055/
# Source: Van Veen et al., 2012 - "43 were chosen flowcharts of the 52 existing in MTS"
# DOI: 10.1136/emermed-2011-200562
# Link: https://emj.bmj.com/content/29/8/654
flowcharts:
  # Most frequently used pediatric flowcharts (Source: PMC5016055 study results)
  worried_parents:
    description: "Most prevalent flowchart - 22.4% of pediatric cases"
    # Source: PMC5016055 - "worried parents was the main flowchart used"
    # Evidence: Brazilian pediatric emergency study of 10,921 consultations
    # Link: https://pmc.ncbi.nlm.nih.gov/articles/PMC5016055/
    1: ["airway_compromise", "absence_of_breathing", "shock", "unresponsive_child"]
    2: ["altered_conscious_level", "severe_pain", "very_hot"]
    3: ["moderate_pain", "hot", "history_of_unconsciousness"] 
    4: ["mild_pain", "warm", "recent_problem"]
    5: ["chronic_problem"]

  shortness_of_breath_in_children:
    description: "Second most common - 19.2% of pediatric cases"
    # Source: Van Veen et al., 2008 - validated pediatric flowchart
    # DOI: 10.1136/bmj.a1501 - BMJ pediatric MTS validation study
    # Link: https://www.bmj.com/content/337/bmj.a1501
    1: ["airway_compromise", "absence_of_breathing", "inadequate_breathing", "shock"]
    2: ["stridor", "very_low_spo2", "altered_conscious_level", "very_hot"]
    3: ["low_spo2", "hot", "moderate_pain", "increased_work_of_breathing"]
    4: ["warm", "mild_dyspnea", "recent_problem"]
    5: ["chronic_breathlessness"]

  diarrhea_and_vomiting:
    description: "Third most common - 11.6% of pediatric cases"
    # Source: PMC5016055 study results
    1: ["airway_compromise", "shock", "unresponsive_child"]
    2: ["severe_dehydration", "persistent_vomiting", "very_hot", "altered_conscious_level"]
    3: ["moderate_dehydration", "hot", "blood_in_vomit", "blood_in_stool"]
    4: ["mild_dehydration", "warm", "recent_problem"]
    5: ["chronic_problem"]

  chest_pain:
    description: "Adult chest pain presentation"
    # Source: Clinical validation studies for cardiac presentations
    # Reference: Mackway-Jones K et al. MTS Manual - Chest Pain flowchart
    # Additional validation: Providência R et al., 2011 - Eur Heart J Acute Cardiovasc Care
    # DOI: 10.1177/2048872611400615
    1: ["airway_compromise", "inadequate_breathing", "shock", "absence_of_pulses"]
    2: ["cardiac_pain", "severe_pain", "very_low_spo2", "new_abnormal_pulse"]
    3: ["pleuritic_pain", "moderate_pain", "low_spo2", "significant_cardiac_history"]
    4: ["mild_pain", "recent_problem"]
    5: ["chronic_chest_pain"]

  abdominal_pain_in_adults:
    description: "Adult abdominal pain presentation"
    1: ["airway_compromise", "inadequate_breathing", "shock"]
    2: ["vomiting_blood", "passing_blood_pr", "severe_pain", "very_hot"]
    3: ["moderate_pain", "hot", "persistent_vomiting"]
    4: ["mild_pain", "warm", "recent_problem"]  
    5: ["chronic_problem"]

  abdominal_pain_in_children:
    description: "Pediatric abdominal pain - 6.2% of pediatric cases"
    # Source: PMC5016055
    1: ["airway_compromise", "inadequate_breathing", "shock", "unresponsive_child"]
    2: ["vomiting_blood", "passing_blood_pr", "purpura", "non_blanching_rash", "hot_baby", "very_hot"]
    3: ["hot", "moderate_pain", "persistent_vomiting"]
    4: ["warm", "mild_pain", "recent_problem"]
    5: ["chronic_problem"]

  unwell_child:
    description: "Non-specific pediatric illness presentation"
    # Source: Standard MTS pediatric assessment
    1: ["airway_compromise", "shock", "unresponsive_child", "currently_fitting"]
    2: ["altered_conscious_level", "purpura", "non_blanching_rash", "hot_baby", "very_hot"]
    3: ["hot", "not_feeding", "moderate_pain", "persistent_vomiting"]
    4: ["warm", "feeding_poorly", "mild_distress"]
    5: ["well_child", "parental_concern_only"]

  unwell_adult:
    description: "Non-specific adult illness presentation"
    # Source: PMC8174732 - "The presentational flow chart unwell adult of the Manchester Triage System"
    # DOI: 10.1186/s12873-021-00464-0
    # Link: https://bmcemergmed.biomedcentral.com/articles/10.1186/s12873-021-00464-0
    # Study: Analysis of 1,246 patients using unwell adult flowchart
    1: ["airway_compromise", "inadequate_breathing", "shock", "currently_fitting"]
    2: ["altered_conscious_level", "severe_pain", "very_hot", "new_abnormal_pulse"]
    3: ["moderate_pain", "hot", "persistent_vomiting", "low_spo2"]
    4: ["mild_pain", "warm", "recent_problem"]
    5: ["chronic_problem", "well_patient"]

  head_injury:
    description: "Head trauma assessment"
    1: ["airway_compromise", "inadequate_breathing", "shock", "currently_fitting"]
    2: ["altered_conscious_level", "history_of_unconsciousness", "severe_pain", "focal_neurological_deficit"]
    3: ["moderate_pain", "persistent_vomiting", "mechanism_of_injury"]
    4: ["mild_pain", "minor_head_injury"]
    5: ["historical_head_injury"]

  limb_problems:
    description: "Extremity injuries and problems"
    1: ["airway_compromise", "shock", "vascular_compromise"]
    2: ["open_fracture", "severe_pain", "neurovascular_deficit"] 
    3: ["fracture", "dislocation", "moderate_pain"]
    4: ["sprain", "soft_tissue_injury", "mild_pain"]
    5: ["chronic_limb_problem"]

  asthma:
    description: "Asthma presentations - 5.2% of pediatric cases"
    # Source: PMC5016055 study results
    1: ["airway_compromise", "inadequate_breathing", "shock"]
    2: ["stridor", "very_low_spo2", "severe_distress", "unable_to_talk"]
    3: ["low_spo2", "moderate_distress", "wheeze"]
    4: ["mild_wheeze", "recent_problem"]
    5: ["chronic_stable_asthma"]

# DISCRIMINATOR PREVALENCE DATA
# Source: PMC5016055 - "105 different discriminators were found during the rating"
# Study: 10,921 pediatric emergency consultations in Brazilian university hospital
# Time period: January 1st 2013 to December 31st 2013
# Link: https://pmc.ncbi.nlm.nih.gov/articles/PMC5016055/
# Top 10 discriminators by frequency in pediatric emergency:
most_common_discriminators:
  recent_event: "15.3% - Most prevalent discriminator"
  hot_child: "8.5% - Temperature >38.5°C in children" 
  low_o2_saturation: "7.4% - SpO2 concerns"
  moderate_pain: "6.4% - Pain score 5-7/10"
  moderate_signs_of_pain: "5.4% - Objective pain assessment"
  not_fed: "5.3% - Feeding issues in infants"
  persistent_vomiting: "5.1% - Ongoing emesis"
  febrile: "4.4% - Fever present"
  productive_cough: "3.9% - Respiratory symptoms"

# KEYWORD RULES - Based on discriminator analysis
# Source: Clinical validation and discriminator frequency data
keyword_rules:
  immediate_priority:
    terms:
      # Life threat discriminators (Priority 1)
      - "cardiac arrest"
      - "not breathing"
      - "airway compromise"
      - "shock"
      - "unresponsive"
      - "fitting"
      - "seizure"
      - "major trauma"
      - "exsanguinating"
    assign: [1]
    threshold: 95

  very_urgent_priority:
    terms:
      # Critical but not immediately life-threatening (Priority 2)
      - "severe pain"
      - "chest pain"
      - "difficulty breathing"
      - "altered consciousness"
      - "very hot"
      - "stridor"
      - "low oxygen"
      - "vomiting blood"
      - "major bleeding"
    assign: [1, 2]
    threshold: 90

  urgent_priority:
    terms:
      # Urgent but stable (Priority 3) 
      - "moderate pain"
      - "persistent vomiting"
      - "hot child"
      - "fever"
      - "head injury"
      - "fracture"
      - "infection"
    assign: [2, 3]
    threshold: 85

  standard_priority:
    terms:
      # Routine care needed (Priority 4)
      - "mild pain"
      - "recent problem"
      - "minor injury"
      - "warm"
      - "feeding problem"
    assign: [3, 4]
    threshold: 80

  non_urgent_priority:
    terms:
      # Can wait (Priority 5)
      - "chronic problem"
      - "well child"
      - "routine"
      - "follow up"
    assign: [4, 5]
    threshold: 75

# VALIDATION METRICS
# Source: Multiple validation studies - systematic review
validation_data:
  sensitivity: 
    # Source: Van Veen et al., 2008 - "moderate sensitivity and specificity in pediatric emergency care"
    # DOI: 10.1136/bmj.a1501
    # Link: https://www.bmj.com/content/337/bmj.a1501
    overall: "Moderate sensitivity for identifying urgent cases"
    high_priority: "High sensitivity for immediate/very urgent categories"
    
  specificity:
    # Source: Multiple validation studies
    overall: "Good specificity for ruling out non-urgent cases"
    
  undertriage_risk:
    # Source: Seiger et al., 2011 - "Undertriage in the Manchester triage system"
    # DOI: 10.1136/adc.2010.206797
    # Link: https://adc.bmj.com/content/96/7/653
    concern: "Risk of underestimating severity in some cases"
    mitigation: "Requires experienced clinical staff"

# IMPLEMENTATION NOTES
# Source: Storm-Versloot et al., 2014 - Implementation effectiveness
# DOI: 10.1136/emermed-2012-201099
# Link: https://emj.bmj.com/content/31/1/13
implementation_requirements:
  staff_training: "Requires specialized MTS training for healthcare professionals"
  clinical_experience: "Nursing staff should have pediatric experience for child presentations"  
  quality_assurance: "Regular audit and validation of triage decisions required"
  system_updates: "MTS undergoes periodic updates - stay current with latest version"

# REFERENCES AND SOURCES
references:
  - "PMC5016055: Manchester Triage System: main flowcharts, discriminators and outcomes of a pediatric emergency care"
  - "Storm-Versloot et al. (2014). Emerg Med J. 31:13-18 - MTS implementation study"
  - "Van Veen et al. (2008). BMJ. 337:a1501 - Pediatric MTS validation"  
  - "Nijman et al. (2011). Arch Dis Child. 96:715-722 - Fever discriminators"
  - "Mackway-Jones K et al. Emergency Triage, Manchester Triage Group. Second edition. Oxford: Blackwell Publishing Ltd; 2006"
  - "Seiger et al. (2011). Arch Dis Child. 96:653-657 - Undertriage assessment"